export const IS_DEV = import.meta.env.DEV
export const IS_PROD = import.meta.env.PROD
export const IS_TEST = import.meta.env.TEST
export const VITE_API_URL = import.meta.env.VITE_API_URL
export const VITE_APP_TITLE = import.meta.env.VITE_APP_TITLE || 'AutoParseHDCShell'
export const VITE_APP_SHORT_NAME = import.meta.env.VITE_APP_SHORT_NAME || 'APHDCS'
export const VITE_APP_VERSION = import.meta.env.VITE_APP_VERSION || '0.0.1'
export const VITE_GA_ID = import.meta.env.VITE_GA_ID || ''
export const VITE_BAIDU_TJ_ID = import.meta.env.VITE_BAIDU_TJ_ID || ''
export const VITE_UMENG_ID = import.meta.env.VITE_UMENG_ID || ''
export const VITE_APP_DESCRIPTION = import.meta.env.VITE_APP_DESCRIPTION || 'AutoParseHDCShell - A powerful tool for parsing HDCShell links.'
export const VITE_APP_KEYWORDS = import.meta.env.VITE_APP_KEYWORDS || 'AutoParseHDCShell, HDCShell, Link Parser, 免费解析, 多平台支持'
export const VITE_APP_AUTHOR = import.meta.env.VITE_APP_AUTHOR || 'yonjay'
export const VITE_APP_LICENSE = import.meta.env.VITE_APP_LICENSE || 'MIT'
export const VITE_APP_COPYRIGHT = import.meta.env.VITE_APP_COPYRIGHT || '2025-now yonjay'
export const VITE_APP_THIRD_PARTY = import.meta.env.VITE_APP_THIRD_PARTY || 'React, Vite, TailwindCSS, shadcn/ui, etc.'
export const VITE_APP_PROXY = import.meta.env.VITE_APP_PROXY || '/api'
export const VITE_APP_STATIC = import.meta.env.VITE_APP_STATIC || '/static/'
export const VITE_APP_ICP = import.meta.env.VITE_APP_ICP || ''
export const VITE_APP_GOV_ICP = import.meta.env.VITE_APP_GOV_ICP || ''
export const VITE_APP_PUBLIC_SECURITY = import.meta.env.VITE_APP_PUBLIC_SECURITY || ''
export const VITE_APP_BUILD_TIME = import.meta.env.VITE_APP_BUILD_TIME || new Date().toISOString()
export const VITE_APP_BUILD_BY = import.meta.env.VITE_APP_BUILD_BY || 'yonjay'
